
package ar.com.todopago.api.payment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PaymentMethodsPortType", targetNamespace = "http://api.todopago.com.ar")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.wso2.ws.dataservice.ObjectFactory.class,
    ar.com.todopago.api.payment.ObjectFactory.class
})
public interface PaymentMethodsPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns ar.com.todopago.api.Result
     * @throws DataServiceFault
     */
    @WebMethod(operationName = "GetComplete", action = "urn:GetComplete")
    @WebResult(name = "Result", targetNamespace = "http://api.todopago.com.ar", partName = "parameters")
    public Result getComplete(
        @WebParam(name = "GetComplete", targetNamespace = "http://api.todopago.com.ar", partName = "parameters")
        GetComplete parameters)
        throws DataServiceFault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns ar.com.todopago.api.PromotionsCollection
     * @throws DataServiceFault
     */
    @WebMethod(operationName = "GetPromotions", action = "urn:GetPromotions")
    @WebResult(name = "PromotionsCollection", targetNamespace = "http://api.todopago.com.ar", partName = "parameters")
    public PromotionsCollection getPromotions(
        @WebParam(name = "GetPromotions", targetNamespace = "http://api.todopago.com.ar", partName = "parameters")
        GetPromotions parameters)
        throws DataServiceFault
    ;

    /**
     * Retrieve all Payment Methods
     * 
     * @param parameters
     * @return
     *     returns ar.com.todopago.api.PaymentMethodsCollection
     * @throws DataServiceFault
     */
    @WebMethod(operationName = "GetAll", action = "urn:GetAll")
    @WebResult(name = "PaymentMethodsCollection", targetNamespace = "http://api.todopago.com.ar", partName = "parameters")
    public PaymentMethodsCollection getAll(
        @WebParam(name = "GetAll", targetNamespace = "http://api.todopago.com.ar", partName = "parameters")
        GetAll parameters)
        throws DataServiceFault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns ar.com.todopago.api.Result
     * @throws DataServiceFault
     */
    @WebMethod(operationName = "Get", action = "urn:Get")
    @WebResult(name = "Result", targetNamespace = "http://api.todopago.com.ar", partName = "parameters")
    public Result get(
        @WebParam(name = "Get", targetNamespace = "http://api.todopago.com.ar", partName = "parameters")
        Get parameters)
        throws DataServiceFault
    ;

}
