
package ar.com.todopago.api.payment;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PaymentMethods", targetNamespace = "http://api.todopago.com.ar", wsdlLocation = "file:/D:/WorkspaceJuno/TodoPago-sdk/res/PaymentMethods.wsdl")
public class PaymentMethods
    extends Service
{

    private final static URL PAYMENTMETHODS_WSDL_LOCATION;
    private final static WebServiceException PAYMENTMETHODS_EXCEPTION;
    private final static QName PAYMENTMETHODS_QNAME = new QName("http://api.todopago.com.ar", "PaymentMethods");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/WorkspaceJuno/TodoPago-sdk/res/PaymentMethods.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYMENTMETHODS_WSDL_LOCATION = url;
        PAYMENTMETHODS_EXCEPTION = e;
    }

    public PaymentMethods() {
        super(__getWsdlLocation(), PAYMENTMETHODS_QNAME);
    }

    public PaymentMethods(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYMENTMETHODS_QNAME, features);
    }

    public PaymentMethods(URL wsdlLocation) {
        super(wsdlLocation, PAYMENTMETHODS_QNAME);
    }

    public PaymentMethods(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYMENTMETHODS_QNAME, features);
    }

    public PaymentMethods(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentMethods(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaymentMethodsPortType
     */
    @WebEndpoint(name = "PaymentMethodsHttpsSoap11Endpoint")
    public PaymentMethodsPortType getPaymentMethodsHttpsSoap11Endpoint() {
        return super.getPort(new QName("http://api.todopago.com.ar", "PaymentMethodsHttpsSoap11Endpoint"), PaymentMethodsPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentMethodsPortType
     */
    @WebEndpoint(name = "PaymentMethodsHttpsSoap11Endpoint")
    public PaymentMethodsPortType getPaymentMethodsHttpsSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.todopago.com.ar", "PaymentMethodsHttpsSoap11Endpoint"), PaymentMethodsPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns PaymentMethodsPortType
     */
    @WebEndpoint(name = "PaymentMethodsHttpSoap11Endpoint")
    public PaymentMethodsPortType getPaymentMethodsHttpSoap11Endpoint() {
        return super.getPort(new QName("http://api.todopago.com.ar", "PaymentMethodsHttpSoap11Endpoint"), PaymentMethodsPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentMethodsPortType
     */
    @WebEndpoint(name = "PaymentMethodsHttpSoap11Endpoint")
    public PaymentMethodsPortType getPaymentMethodsHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.todopago.com.ar", "PaymentMethodsHttpSoap11Endpoint"), PaymentMethodsPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYMENTMETHODS_EXCEPTION!= null) {
            throw PAYMENTMETHODS_EXCEPTION;
        }
        return PAYMENTMETHODS_WSDL_LOCATION;
    }

}
