
package ar.com.todopago.api.operations;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OperationsPortType", targetNamespace = "http://api.todopago.com.ar")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.wso2.ws.dataservice.ObjectFactory.class,
    ar.com.todopago.api.operations.ObjectFactory.class
})
public interface OperationsPortType {


    /**
     * Consulta por id De Operacion y Comercio
     * 			
     * 
     * @param parameters
     * @return
     *     returns ar.com.todopago.api.OperationsColections
     * @throws DataServiceFault
     */
    @WebMethod(operationName = "GetByOperationId", action = "urn:GetByOperationId")
    @WebResult(name = "OperationsColections", targetNamespace = "http://api.todopago.com.ar", partName = "parameters")
    public OperationsColections getByOperationId(
        @WebParam(name = "GetByOperationId", targetNamespace = "http://api.todopago.com.ar", partName = "parameters")
        GetByOperationId parameters)
        throws DataServiceFault
    ;

}
