
package ar.com.todopago.api.echoservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EchoServiceDSSPortType", targetNamespace = "http://ws.wso2.org/dataservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EchoServiceDSSPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns org.wso2.ws.dataservice.EchoResponse
     * @throws DataServiceFault_Exception
     */
    @WebMethod(operationName = "echo_operation", action = "urn:echo_operation")
    @WebResult(name = "echo_response", targetNamespace = "http://ws.wso2.org/dataservice", partName = "parameters")
    public EchoResponse echoOperation(
        @WebParam(name = "echo_operation", targetNamespace = "http://ws.wso2.org/dataservice", partName = "parameters")
        EchoOperation parameters)
        throws DataServiceFault_Exception
    ;

}
