
package ar.com.todopago.api.echoservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EchoServiceDSS", targetNamespace = "http://ws.wso2.org/dataservice", wsdlLocation = "file:/C:/Users/juan.peregrina/WsdlRegen/EchoServiceDSS.wsdl")
public class EchoServiceDSS
    extends Service
{

    private final static URL ECHOSERVICEDSS_WSDL_LOCATION;
    private final static WebServiceException ECHOSERVICEDSS_EXCEPTION;
    private final static QName ECHOSERVICEDSS_QNAME = new QName("http://ws.wso2.org/dataservice", "EchoServiceDSS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/juan.peregrina/WsdlRegen/EchoServiceDSS.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ECHOSERVICEDSS_WSDL_LOCATION = url;
        ECHOSERVICEDSS_EXCEPTION = e;
    }

    public EchoServiceDSS() {
        super(__getWsdlLocation(), ECHOSERVICEDSS_QNAME);
    }

    public EchoServiceDSS(WebServiceFeature... features) {
        super(__getWsdlLocation(), ECHOSERVICEDSS_QNAME, features);
    }

    public EchoServiceDSS(URL wsdlLocation) {
        super(wsdlLocation, ECHOSERVICEDSS_QNAME);
    }

    public EchoServiceDSS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ECHOSERVICEDSS_QNAME, features);
    }

    public EchoServiceDSS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EchoServiceDSS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EchoServiceDSSPortType
     */
    @WebEndpoint(name = "EchoServiceDSSHttpsSoap11Endpoint")
    public EchoServiceDSSPortType getEchoServiceDSSHttpsSoap11Endpoint() {
        return super.getPort(new QName("http://ws.wso2.org/dataservice", "EchoServiceDSSHttpsSoap11Endpoint"), EchoServiceDSSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EchoServiceDSSPortType
     */
    @WebEndpoint(name = "EchoServiceDSSHttpsSoap11Endpoint")
    public EchoServiceDSSPortType getEchoServiceDSSHttpsSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.wso2.org/dataservice", "EchoServiceDSSHttpsSoap11Endpoint"), EchoServiceDSSPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns EchoServiceDSSPortType
     */
    @WebEndpoint(name = "EchoServiceDSSHttpSoap11Endpoint")
    public EchoServiceDSSPortType getEchoServiceDSSHttpSoap11Endpoint() {
        return super.getPort(new QName("http://ws.wso2.org/dataservice", "EchoServiceDSSHttpSoap11Endpoint"), EchoServiceDSSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EchoServiceDSSPortType
     */
    @WebEndpoint(name = "EchoServiceDSSHttpSoap11Endpoint")
    public EchoServiceDSSPortType getEchoServiceDSSHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.wso2.org/dataservice", "EchoServiceDSSHttpSoap11Endpoint"), EchoServiceDSSPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ECHOSERVICEDSS_EXCEPTION!= null) {
            throw ECHOSERVICEDSS_EXCEPTION;
        }
        return ECHOSERVICEDSS_WSDL_LOCATION;
    }

}
