
package ar.com.todopago.api.authorize;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuthorizePortType", targetNamespace = "http://api.todopago.com.ar")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthorizePortType {


    /**
     * Service definition of Operation SendAuthorizeRequest: Utilizada para enviar los datos que se utilizaran en el  requerimiento de Autorizacion, para Clientes PCI
     * 
     * @param parameters
     * @return
     *     returns ar.com.todopago.api.SendAuthorizeRequestResponse
     */
    @WebMethod(operationName = "SendAuthorizeRequest")
    @WebResult(name = "SendAuthorizeRequestResponse", targetNamespace = "http://api.todopago.com.ar", partName = "parameters")
    public SendAuthorizeRequestResponse sendAuthorizeRequest(
        @WebParam(name = "SendAuthorizeRequest", targetNamespace = "http://api.todopago.com.ar", partName = "parameters")
        SendAuthorizeRequest parameters);

    /**
     * Service definition of Operation GetAuthorizeAnswer: Utilizada para recuerar los datos de la Respuesta de la Autorizacion en el Caso de Clientes no PCI
     * 
     * @param parameters
     * @return
     *     returns ar.com.todopago.api.GetAuthorizeAnswerResponse
     */
    @WebMethod(operationName = "GetAuthorizeAnswer")
    @WebResult(name = "GetAuthorizeAnswerResponse", targetNamespace = "http://api.todopago.com.ar", partName = "parameters")
    public GetAuthorizeAnswerResponse getAuthorizeAnswer(
        @WebParam(name = "GetAuthorizeAnswer", targetNamespace = "http://api.todopago.com.ar", partName = "parameters")
        GetAuthorizeAnswer parameters);

    /**
     * Service definition of Operation Void: Utilizada para Anular una Transaccion
     * 
     * @param parameters
     * @return
     *     returns ar.com.todopago.api.VoidResponse
     */
    @WebMethod(operationName = "VoidRequest")
    @WebResult(name = "VoidResponse", targetNamespace = "http://api.todopago.com.ar", partName = "parameters")
    public VoidResponse voidRequest(
        @WebParam(name = "VoidRequest", targetNamespace = "http://api.todopago.com.ar", partName = "parameters")
        VoidRequest parameters);

    /**
     * Service definition of Operation Return: Utilizada para Devolver total o parcialmente una Transaccion
     * 
     * @param parameters
     * @return
     *     returns ar.com.todopago.api.ReturnResponse
     */
    @WebMethod(operationName = "ReturnRequest")
    @WebResult(name = "ReturnResponse", targetNamespace = "http://api.todopago.com.ar", partName = "parameters")
    public ReturnResponse returnRequest(
        @WebParam(name = "ReturnRequest", targetNamespace = "http://api.todopago.com.ar", partName = "parameters")
        ReturnRequest parameters);

}
